OPENJPA-1764 protect against java.lang.NoClassDefFoundError when being used in an app server but as app managed and the JVM exits quickly from under us
git-svn-id: https://svn.apache.org/repos/asf/openjpa/trunk@1030183 13f79535-47bb-0310-9956-ffa450edef68